### ISSUE TITLE
NullPointerException: cannot replace Game class

### ISSUE THREAD

**Issue by clawoflight** [iXeption/libgdx-transitions#1]
If I make my main class extend FadingGame instead of Game, I get a NullPointerException in new Spritebatch() while calling the superconstructor.

**Comment by digital-thinking** [comment]
ScreenManager extends FadingGame {
public ScreenManager() {
        super(new SpriteBatch());
    }
}

This works for me. Can u post your stacktrace?

**Comment by eliasbrange** [comment]
Same problem here. Main class looks like this:

```
public class Template extends FadingGame {

    public ActionResolver actionResolver;

    public Template(ActionResolver actionResolver) {
        super(new SpriteBatch());
        this.actionResolver = actionResolver;
    }

    @Override
    public void create () {
    ...
    }        
```

Stacktrace:

> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                   Process: com.xxx.template, PID: 3430
>                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.template/com.xxx.template.AndroidLauncher}: java.lang.NullPointerException: Attempt to invoke interface method 'int com.badlogic.gdx.Graphics.getWidth()' on a null object reference
>                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
>                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
>                                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
>                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
>                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                       at android.os.Looper.loop(Looper.java:158)
>                                                                       at android.app.ActivityThread.main(ActivityThread.java:7229)
>                                                                       at java.lang.reflect.Method.invoke(Native Method)
>                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
>                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
>                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int com.badlogic.gdx.Graphics.getWidth()' on a null object reference
>                                                                       at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:105)
>                                                                       at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:78)
>                                                                       at com.xxx.template.Template.<init>(Template.java:0)
>                                                                       at com.xxx.template.AndroidLauncher.onCreate(AndroidLauncher.java:48)
>                                                                       at android.app.Activity.performCreate(Activity.java:6876)
>                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
>                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
>                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
>                                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
>                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
>                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                       at android.os.Looper.loop(Looper.java:158) 
>                                                                       at android.app.ActivityThread.main(ActivityThread.java:7229) 
>                                                                       at java.lang.reflect.Method.invoke(Native Method) 
>                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
>                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by digital-thinking** [comment]
Not sure if the actual version of libgdx changed some things and if the lib is still working for that version.
Sorry, but i don´t have the time to look after that, if you find the problem it would be great if you submit a pull request. Thanks.
