### ISSUE TITLE
Single black frame during animation

### ISSUE THREAD

**Issue by mhilbrunner** [iXeption/libgdx-transitions#2]
Hi,

thank you for publishing this library, saved me quite some time.

I noticed while testing, in [FadingGame.java, Line 95](https://github.com/iXeption/libgdx-transitions/blob/master/src/main/com/ixeption/libgdx/transitions/FadingGame.java#L95):
There is a missing `screen.render()` call for the case that the animation is finished.

So the current behaviour is this:
1. Rendering while the animation plays
2. Not rendering when the animation is finished and nextStage is switched to stage
3. Rendering again after that

Which causes a single blank frame to be renderer, causing 'flickering'.

**Suggested fix:**
Add `screen.render()` in FadingGame.java Line 95.

Again, thank you for your work!

**Comment by digital-thinking** [comment]
HI, thanks for your contribution!
I will change this in the next days.
