### ISSUE TITLE
Font and alpha level of textures are not shown correctly until the transition is finished

### ISSUE THREAD

**Issue by dizzersee** [iXeption/libgdx-transitions#3]
While the transition is running, the font of the second screen is not shown correctly. There is only some default font, but not the font from my skin. After the transition is finished, everything looks normal again. The same happens with the alpha level: During the transition, the alpha level of textures is always 100%.
However, this only happens to the second screen. 
Maybe I am doing something wrong?

And thank you for publishing the library, its great!

Edit: Oh now it seems to work properly. In the transition class, I removed the following lines:

`Gdx.gl.glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);`

**Comment by digital-thinking** [comment]
Thanks!
I will test it out and then fix it.
